language: generic
env:
  global:
    - IDE_VERSION=1.8.5
    - SDAPP_FOLDER=$PWD/examples/M5Stack-SD-Menu/SD-Apps
    - TRAVIS_TAG="SD-Extras-1.0.0"
  matrix:
    - EXAMPLE="M5Stack-SD-Menu" BOARD="espressif:esp32:m5stack-core-esp32:FlashFreq=80"
#    - EXAMPLE="M5Stack-SDLoader-Snippet" BOARD="espressif:esp32:m5stack-core-esp32:FlashFreq=80"
before_install:
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - mv arduino-$IDE_VERSION ~/arduino-ide
  - export PATH=$PATH:~/arduino-ide
  - mkdir -p $TRAVIS_BUILD_DIR/build
  - if [[ "$BOARD" =~ "espressif:esp32:" ]]; then
      mkdir -p ~/Arduino/hardware/espressif &&
      cd ~/Arduino/hardware/espressif &&
      git clone https://github.com/espressif/arduino-esp32.git esp32 &&
      cd esp32/ &&
      git submodule update --init --recursive &&
      cd tools/ &&
      python get.py &&
      cd $TRAVIS_BUILD_DIR;
    fi
  
install:
  - git submodule update --init --recursive
  - mkdir -p ~/Arduino/libraries
  - ln -s $PWD ~/Arduino/libraries/.
  - wget https://github.com/bblanchon/ArduinoJson/archive/master.zip --output-document=Arduinojson-master.zip
  - unzip -d ~/Arduino/libraries Arduinojson-master.zip
  - wget https://github.com/tomsuch/M5StackSAM/archive/master.zip --output-document=M5StackSAM-master.zip
  - unzip -d ~/Arduino/libraries M5StackSAM-master.zip
#  - wget https://github.com/ricmoo/QRCode/archive/master.zip --output-document=QRCode-master.zip
#  - unzip -d ~/Arduino/libraries QRCode-master.zip
  - wget https://github.com/m5stack/M5Stack/archive/0.1.7.zip --output-document=M5Stack.zip
  - unzip -d ~/Arduino/libraries M5Stack.zip
  - wget https://github.com/earlephilhower/ESP8266Audio/archive/master.zip --output-document=ESP8266Audio.zip
  - unzip -d ~/Arduino/libraries ESP8266Audio.zip
  - wget https://github.com/Kongduino/M5Widgets/archive/master.zip --output-document=M5Widgets.zip
  - unzip -d ~/Arduino/libraries M5Widgets.zip
  - wget https://github.com/Gianbacchio/ESP8266_Spiram/archive/master.zip --output-document=ESP8266_Spiram.zip
  - unzip -d ~/Arduino/libraries ESP8266_Spiram.zip
  - wget http://www.buildlog.net/blog/wp-content/uploads/2018/02/Game_Audio.zip --output-document=Game_Audio.zip
  - mkdir -p ~/Arduino/libraries/Game_Audio
  - unzip -d ~/Arduino/libraries/Game_Audio Game_Audio.zip
  - ls ~/Arduino/libraries -la

script:
  - arduino --pref "compiler.warning_level=none" --save-prefs
  - arduino --pref "build.warn_data_percentage=75" --save-prefs
  - arduino  --preserve-temp-files --verbose-build --verify --board $BOARD $PWD/examples/$EXAMPLE/$EXAMPLE.ino >> $SDAPP_FOLDER/out.log
  - find /tmp -name \*.partitions.bin -exec rm {} \; #
  - find /tmp -name \*.bin -exec mv {} $TRAVIS_BUILD_DIR/build/menu.bin \; #
  - echo "Main APP Compilation successful, now compiling deps"
  - cd $SDAPP_FOLDER
  - ./gen-apps.sh
  #- find /tmp -name \*.bin -exec ls -lrt {} \; #<-- you need that backslash before and space after the semicolon
  #- find /tmp -name \*.bin -exec cp {} $TRAVIS_BUILD_DIR/build/$BINNAME \; #<-- you need that backslash before and space after the semicolon
  #- find $TRAVIS_BUILD_DIR/build -name \*.bin -exec ls -lrt {} \; #<-- you need that backslash before and space after the semicolon
  - ls $TRAVIS_BUILD_DIR/build/ -la
  - sleep 15 # give some time to the logs to come up  

before_deploy:
  # Set up git user name and tag this commit
  - cd $TRAVIS_BUILD_DIR
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git tag ${TRAVIS_TAG}
  - cd $TRAVIS_BUILD_DIR/build 
  - zip -r ../SD-Apps-Folder.zip ./
  - cd ..

  # - export BODY=$(cat CHANGELOG.md) # boo! Travis doesn't like multiline body
  
deploy:
  provider: releases
  api_key: $GH_TOKEN
  overwrite: true
  skip_cleanup: true
  target_commitish: $TRAVIS_COMMIT
  tag_name: $TRAVIS_TAG
  name: SD-Extras-autorelease $TRAVIS_TAG
  body: Automated release from Travis CI with added SD Apps binary files from Arduino compilation 
  draft: true
  #file_glob: true
  #file: $TRAVIS_BUILD_DIR/build/*
  file: $TRAVIS_BUILD_DIR/SD-Apps-Folder.zip
  on:
    branch: M5Stack-SD-Apps
