language: generic
env:
  global:
    - IDE_VERSION=1.8.5
  matrix:
    - EXAMPLE="M5Stack-SD-Menu" BOARD="espressif:esp32:m5stack-core-esp32:FlashFreq=80"
    - EXAMPLE="M5Stack-SDLoader-Snippet" BOARD="espressif:esp32:m5stack-core-esp32:FlashFreq=80"
before_install:
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - mv arduino-$IDE_VERSION ~/arduino-ide
  - export PATH=$PATH:~/arduino-ide
  - if [[ "$BOARD" =~ "espressif:esp32:" ]]; then
      mkdir -p ~/Arduino/hardware/espressif &&
      cd ~/Arduino/hardware/espressif &&
      git clone https://github.com/espressif/arduino-esp32.git esp32 &&
      cd esp32/tools/ &&
      python get.py &&
      cd $TRAVIS_BUILD_DIR;
    fi
  
install:
  - mkdir -p ~/Arduino/libraries
  - ln -s $PWD ~/Arduino/libraries/.
  - wget https://github.com/bblanchon/ArduinoJson/archive/master.zip --output-document=Arduinojson-master.zip
  - unzip -d ~/Arduino/libraries Arduinojson-master.zip
  - wget https://github.com/tomsuch/M5StackSAM/archive/master.zip --output-document=M5StackSAM-master.zip
  - unzip -d ~/Arduino/libraries M5StackSAM-master.zip
  - wget https://github.com/ricmoo/QRCode/archive/master.zip --output-document=QRCode-master.zip
  - unzip -d ~/Arduino/libraries QRCode-master.zip
  - wget https://github.com/m5stack/M5Stack/archive/master.zip --output-document=M5Stack.zip
  - unzip -d ~/Arduino/libraries M5Stack.zip
  
script:
  - arduino --verbose-build --verify --board $BOARD $PWD/examples/$EXAMPLE/$EXAMPLE.ino;
 
